id: yukon_migrate_document
label: Yukon migrate Document Media Type
audit: true
migration_tags:
  - Drupal 7
  - Media
migration_group: legacy

source:
  plugin: yukon_migrate_file
  scheme: public
  file_type:
    - document
  file_mime:
    - 'application/pdf'
    - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    - 'application/vnd.ms-excel'
    - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    - 'application/msword'
  batch_size: 200
  constants:
    source_base_path: 'https://yukon.ca/'

process:
  name: filename_field
  field_document_name: field_document_name

  field_folder:


  directory:
    plugin: migration_lookup
    migration: yukon_migrate_media_folders
    source: field_folder/0/tid
    no_stub: true

  filemime: filemime
  status: status
  created: timestamp
  changed: timestamp
  # Todo: Replace this part with migration lookup after we migrate users.
  uid: uid
  langcode:
    plugin: default_value
    default_value: "en"

destination:
  plugin: 'entity:media'
  default_bundle: document

migration_dependencies:
  required:
    - yukon_migrate_files__public
