id: yukon_migrate_document
label: Yukon migrate Document Media Type
audit: true
migration_tags:
  - Drupal 7
  - Content
  - Media
migration_group: legacy
source:
  plugin: yukon_migrate_file_mime
  scheme: public
  file_type:
    - document
  file_mime:
    - 'application/pdf'
  batch_size: 200
  constants:
    source_base_path: 'https://yukon.ca/'
process:
  name: filename
  field_media_image/target_id:
    - plugin: migration_lookup
      migration: yukon_migrate_files__public
      source: fid
      no_stub: true
    - plugin: skip_on_empty
      method: row
  field_media_image/alt: field_file_image_alt_text/0/value
  field_media_image/title: field_file_image_title_text/0/value

  directory:
    plugin: migration_lookup
    migration: yukon_migrate_media_folders
    source: field_folder/0/tid
    no_stub: true

  filemime: filemime
  status: status
  created: timestamp
  changed: timestamp
  # Todo: Replace this part with migration lookup after we migrate users.
  uid: uid
  langcode:
    plugin: default_value
    default_value: "en"
destination:
  plugin: entity:media
  default_bundle: document
migration_dependencies:
  required:
#    - yukon_migrate_files__public
    - yukon_migrate_media_folders
